# Generated by Django 3.2.2 on 2021-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pestm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestDetM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_No', models.IntegerField(null=True)),
                ('Youto', models.CharField(max_length=200, null=True)),
                ('PestType', models.CharField(max_length=200, null=True)),
                ('PestName', models.CharField(max_length=200, null=True)),
                ('ShortName', models.CharField(max_length=200, null=True)),
                ('VegiName', models.CharField(max_length=200, null=True)),
                ('TekiyouByogaichu', models.CharField(max_length=200, null=True)),
                ('SiyouMokuteki', models.CharField(max_length=200, null=True)),
                ('KisyakuBaisuu', models.CharField(max_length=200, null=True)),
                ('SanpuEkiryou', models.CharField(max_length=200, null=True)),
                ('SiyouJiki', models.CharField(max_length=200, null=True)),
                ('SiyouKaisuu', models.CharField(max_length=200, null=True)),
                ('SiyouHouhou', models.CharField(max_length=200, null=True)),
                ('TekiyouBasyo', models.CharField(max_length=200, null=True)),
                ('KunjyoJikan', models.CharField(max_length=200, null=True)),
                ('KunjyoOndo', models.CharField(max_length=200, null=True)),
                ('TekiyouDojyou', models.CharField(max_length=200, null=True)),
                ('TekiyouChitai', models.CharField(max_length=200, null=True)),
                ('KongouSuu', models.IntegerField(null=True)),
                ('SeibunKaisu1', models.CharField(max_length=200, null=True)),
                ('SeibunKaisu2', models.CharField(max_length=200, null=True)),
                ('SeibunKaisu3', models.CharField(max_length=200, null=True)),
                ('SeibunKaisu4', models.CharField(max_length=200, null=True)),
                ('SeibunKaisu5', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pestm',
            name='KaisuSeibun',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='KongouSu',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='MakerName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='Noudo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='PestName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='PestType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='T_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='TourokuYMD',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='Youto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='YukoSeibun',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pestm',
            name='Zaigata',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
